apiVersion: v1
kind: Service
metadata:
  name: registry-inside
  namespace: hor
  labels:
    app: registry
spec:
  ports:
  - port: 5000
    name: registry
  clusterIP: None
  selector:
    app: registry
---
apiVersion: v1
kind: Service
metadata:
  name: registry-outside
  namespace: hor
  labels:
    app: registry
spec:
  ports:
  - port: 5000
    name: registry
  selector:
    app: registry
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: registry
  namespace: hor
spec:
  serviceName: registry-inside
  replicas: 2
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: registry
        image: registry:2
        ports:
        - containerPort: 5000
          name: registry
        volumeMounts:
        - name: registry-pvc
          mountPath: /var/lib/registry
  volumeClaimTemplates:
  - metadata:
      name: registry-pvc
    spec:
      accessModes:
      - ReadWriteMany
      storageClassName: nfs
      resources:
        requests:
          storage: 10Gi