apiVersion: mysql.oracle.com/v1alpha1
kind: Cluster
metadata:
  name: mysql-cluster-with-volume
spec:
  members: 1
  config:
    name: mycnf
  volumeClaimTemplate:
    metadata:
      name: data
    spec:
      storageClassName: nfs
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 1Gi