kind: Service
apiVersion: v1
metadata:
  name: nginx-demo
spec:
  selector:
    name: init-demo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: init-demo
  labels:
    name: init-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: init-demo
  template:
    metadata:
      labels:
        name: init-demo
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: workdir
          mountPath: /usr/share/nginx/html
      initContainers:
      - name: install
        image: busybox
        command:
        - wget
        - "-O"
        - "/work-dir/index.html"
        - http://www.baidu.com
        volumeMounts:
        - name: workdir
          mountPath: "/work-dir"
      volumes:
      - name: workdir
        emptyDir: {}