apiVersion: v1
kind: Pod
metadata:
  name: check-volume
spec:
  volumes:
  - name: code-claim
    persistentVolumeClaim:
      claimName: code-claim
  containers:
  - name: sec-ctx-demo
    image: busybox
    command: ["sh", "-c", "sleep 1h"]
    volumeMounts:
    - name: code-claim
      mountPath: /work
