apiVersion: v1
kind: Pod
metadata:
  name: check-volume
  namespace: pipeline
spec:
  volumes:
  - name: test-repo
    persistentVolumeClaim:
      claimName: test-repo
  containers:
  - name: sec-ctx-demo
    image: busybox
    command: ["sh", "-c", "sleep 1h"]
    volumeMounts:
    - name: test-repo
      mountPath: /work
