apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: cuijx/nginx-net-tools
    imagePullPolicy: IfNotPresent
  nodeSelector:
    disktype: ssd